# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Compute SSR recursively
#' 
#' @description This procedure computes recursive residuals from a data set that starts
#' at date "start" and ends at date "last". It returns a vector of sum of
#' squared residuals (SSR) of length last-start+1 (stored for convenience in a vector of length T).
#' 
#' @param start starting entry of the sample used.
#' @param y dependent variable
#' @param z matrix of regressors of dimension q
#' @param h minimal length of a segment
#' @param last ending date of the last segment considered.
#' 
#' @details Note: This code is an adaptation of the one originally written by Yohei 
#' Yamamoto and Pierre Perron for MATLAB. Original codes can be found on 
#' Pierre Perron's website: https://blogs.bu.edu/perron/codes/
#' 
#' @references Bai, Jushan & Pierre Perron (1998), "Estimating and Testing Linear Models with Multiple Structural Changes," \emph{Econometrica}, vol 66, 47-78.
#' @references Bai, Jushan & Pierre Perron (2003), "Computation and Analysis of Multiple Structural Change Models," \emph{Journal of Applied Econometrics}, 18, 1-22.
#' 
#' @export
ssr_vec <- function(start, y, z, h, last) {
    .Call(`_mbreaks_ssr_vec`, start, y, z, h, last)
}

#' @export
ssrbigvec <- function(y, z, h) {
    .Call(`_mbreaks_ssrbigvec`, y, z, h)
}

#' @title MLE function
#' 
#' @references Perron, Pierre, Yohei Yamamoto, and Jing Zhou (2020), "Testing Jointly for Structural Changes in the Error Variance and Coefficients of a Linear Regression Model" \emph{Quantitative Economics}, vol 11, 1019-1057.
#' @export
mlef <- function(start, y, z, q, x, p, h, last) {
    .Call(`_mbreaks_mlef`, start, y, z, q, x, p, h, last)
}

#' @title MLE function
#' 
#' @references Perron, Pierre, Yohei Yamamoto, and Jing Zhou (2020), "Testing Jointly for Structural Changes in the Error Variance and Coefficients of a Linear Regression Model" \emph{Quantitative Economics}, vol 11, 1019-1057.
#' @export
mlebigvec <- function(y, z, q, x, p, h, bigt) {
    .Call(`_mbreaks_mlebigvec`, y, z, q, x, p, h, bigt)
}

#' @title optimal break partitions for a given segment
#' 
#' @description procedure to obtain an optimal one break partitions for a segment that 
#' starts at date start and ends at date last. It returns the optimal break and the 
#' associated SSR.
#' 
#' @param start: beginning of the segment considered
#' @param b1: first possible break date
#' @param b2: last possible break date
#' @param last: end of segment considered
#' 
#' @details Note: This code is translated from MATLABS code written by Yohei 
#' Yamamoto and Pierre Perron. Original codes can be found on 
#' Pierre Perron's website: https://blogs.bu.edu/perron/codes/
#' 
#' @references Bai, Jushan & Pierre Perron (1998), "Estimating and Testing Linear Models with Multiple Structural Changes," \emph{Econometrica}, vol 66, 47-78.
#' @references Bai, Jushan & Pierre Perron (2003), "Computation and Analysis of Multiple Structural Change Models," \emph{Journal of Applied Econometrics}, 18, 1-22.
#' 
#' @export
parti <- function(start, b1, b2, last, bigvec, bigt) {
    .Call(`_mbreaks_parti`, start, b1, b2, last, bigvec, bigt)
}

#' @title optimal break partitions for a given segment using log-likelihood
#' 
#' @description procedure to obtain an optimal one break partitions for a segment that 
#' starts at date start and ends at date last. It returns the optimal break and the 
#' associated log-likelihood (parti2() in original MATLAB code)
#' 
#' @references Perron, Pierre, Yohei Yamamoto, and Jing Zhou (2020), "Testing Jointly for Structural Changes in the Error Variance and Coefficients of a Linear Regression Model" \emph{Quantitative Economics}, vol 11, 1019-1057.
#' 
#' @export
parti_loglik <- function(start, b1, b2, last, bigvec, bigt) {
    .Call(`_mbreaks_parti_loglik`, start, b1, b2, last, bigvec, bigt)
}

#' @title Compute global break dates for pure structural change model
#' 
#' @description This is the main procedure which calculates the break points that globally
#'  minimizes the SSR. It returns optimal dates and associated SSR for all numbers of breaks less than or equal to m.
#' 
#' @details Note: This code is an adaptation of the one originally written by Yohei 
#' Yamamoto and Pierre Perron for MATLAB. Original code files can be found on 
#' Pierre Perron's website: https://blogs.bu.edu/perron/codes/
#' 
#' @param y A (\code{T x 1}) vector with endogenous variable.
#' @param z A (\code{T x q}) matrix with explanatory variables subject to change.
#' @param m An integer determining the number of breaks to find.
#' @param h An integer determining the minimum length of a regime. 
#' 
#' @references Bai, Jushan & Pierre Perron (1998), "Estimating and Testing Linear Models with Multiple Structural Changes," \emph{Econometrica}, vol 66, 47-78.
#' @references Bai, Jushan & Pierre Perron (2003), "Computation and Analysis of Multiple Structural Change Models," \emph{Journal of Applied Econometrics}, 18, 1-22.
#' 
#' @export
dating_purescSSR <- function(y, z, m, h) {
    .Call(`_mbreaks_dating_purescSSR`, y, z, m, h)
}

#' @title Compute global break dates using log-likelihood 
#' 
#' @description This is the main procedure which calculates the break points that globally maximize the loglikelihood function. It returns optimal dates and associated log likelihood for all numbers of breaks less than or equal to m. 
#' 
#' @references Perron, Pierre, Yohei Yamamoto, and Jing Zhou (2020), "Testing Jointly for Structural Changes in the Error Variance and Coefficients of a Linear Regression Model" \emph{Quantitative Economics}, vol 11, 1019-1057.
#' 
#' @export
dating_loglik <- function(bigvec, h, m, bigt) {
    .Call(`_mbreaks_dating_loglik`, bigvec, h, m, bigt)
}

#' @title Compute global break dates using log-likelihood 
#' 
#' @description This is the main procedure which calculates the break points that globally maximize the loglikelihood function. It returns optimal dates and associated log likelihood for all numbers of breaks less than or equal to m. 
#' 
#' @references Perron, Pierre, Yohei Yamamoto, and Jing Zhou (2020), "Testing Jointly for Structural Changes in the Error Variance and Coefficients of a Linear Regression Model" \emph{Quantitative Economics}, vol 11, 1019-1057.
#' 
#' @export
dating_MLE <- function(y, z, q, x, p, h, m, bigt) {
    .Call(`_mbreaks_dating_MLE`, y, z, q, x, p, h, m, bigt)
}

